services:
  store:
    container_name: store
    image: bhs/store
    build: .
    # links:
    #   - "postgres"
    ports:
      - 8000:8000
    networks:
      - bhslink
    depends_on:
      - postgres
      
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: teste123
      POSTGRES_USER: postgres
      POSTGRES_DB: store
    # ports: 
    #   - 5432:5432
    networks:
     - bhslink
  
networks:
  bhslink:

  