services:
  store:
    container_name: amarassist
    image: REGISTRYAWS/IMAGEM:$GENERAL_TAG
    restart: always
    ports:
      - 80:8000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: amarassist
      DB_USERNAME: amarassist
      DB_PASSWORD: teste123
    networks:
      - bhslink
    depends_on:
      - mysql    
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql        
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: amarassist
      MYSQL_USER: amarassist
      MYSQL_PASSWORD: teste123        

    networks:
     - bhslink

volume:
  db_data:

networks:
  bhslink: